apiVersion: v1
kind: Service
metadata:
  name: closet-closet
  namespace: closet
  labels:
    app: closet
spec:
  selector:
    app: closet
    tier: backend
  ports:
    - protocol: TCP
      port: 14000
      targetPort: 14000
  type: ClusterIP