version: '3'
services:
  gateway:
    image: docker.io/jiheonk/msa/gateway:latest
    build:
      context: ./ApiGateway
    ports:
      - "11000:11000"
    depends_on:
      - eureka
      - user
      - closet
      - community
      - style

  eureka:
    image: docker.io/jiheonk/msa/eureka:latest
    build:
      context: ./EurekaServer
    ports:
      - "8761:8761"

  user:
    image: docker.io/jiheonk/msa/user:latest
    build:
      context: ./UserService
    ports:
      - "13000:13000"
    environment:
      - EUREKA_SERVER_URL=http://eureka:8761/eureka/

  closet:
    image: docker.io/jiheonk/msa/closet:latest
    build:
      context: ./ClosetService
    ports:
      - "14000:14000"
    environment:
      - EUREKA_SERVER_URL=http://eureka:8761/eureka/

  community:
    image: docker.io/jiheonk/msa/community:latest
    build:
      context: ./CommunityService
    ports:
      - "16000:16000"
    environment:
      - EUREKA_SERVER_URL=http://eureka:8761/eureka/

  style:
    image: docker.io/jiheonk/msa/style:latest
    build:
      context: ./StyleService
    ports:
      - "18000:18000"
    environment:
      - EUREKA_SERVER_URL=http://eureka:8761/eureka/

  front:
    image: docker.io/jiheonk/msa/front:latest
    build:
      context: ./FrontService
    ports:
      - "12000:12000"

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - eureka
      - user
      - closet
      - community
      - style
      - front
      - zookeeper
      - kafka
    networks:
      - jenkins_network

volumes:
  jenkins_home:

networks:
  jenkins_network:
