apiVersion: v1
kind: Service
metadata:
  name: closet-community
  namespace: closet
  labels:
    app: closet
spec:
  selector:
    app: closet
    tier: backend
  ports:
    - protocol: TCP
      port: 16000
      targetPort: 16000
  type: ClusterIP