apiVersion: v1
kind: Service
metadata:
  name: closet-style
  namespace: closet
  labels:
    app: closet
spec:
  selector:
    app: closet
    tier: backend
  ports:
    - protocol: TCP
      port: 18000
      targetPort: 18000
  type: ClusterIP
  