spring:
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    config:
      name: community
      profile: prod
    gcp:
      storage:
        credentials:
          location: CommunityService/src/main/resources/closetproject-419105-297cdb4ae5b4.json