apiVersion: apps/v1
kind: Deployment
metadata:
  name: closet-gateway
  namespace: closet
  labels:
    app: closet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: closet
      tier: backend
  template:
    metadata:
      name: closet
      labels:
        app: closet
        tier: backend
    spec:
      containers:
        - name: closet
          image: asia-northeast3-docker.pkg.dev/closetproject-419105/closet/closet-gateway:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 11000
      restartPolicy: Always