apiVersion: v1
kind: Service
metadata:
  name: closet-svc
  namespace: closet
  labels:
    app: closet
spec:
  selector:
    app: closet
    tier: backend
  ports:
    - protocol: TCP
      port: 11000
      targetPort: 11000
      nodePort: 31100
  type: NodePort