apiVersion: v1
kind: Service
metadata:
  name: closet-eureka
  namespace: closet
  labels:
    app: closet
spec:
  selector:
    app: closet
    tier: backend
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer
