apiVersion: v1
kind: Service
metadata:
  name: closet-front
  namespace: closet
  labels:
    app: closet
spec:
  selector:
    app: closet
    tier: backend
  ports:
    - protocol: TCP
      port: 12000
      targetPort: 12000
  type: LoadBalancer