apiVersion: v1
kind: Service
metadata:
  name: closet-user
  namespace: closet
  labels:
    app: closet
spec:
  selector:
    app: closet
    tier: backend
  ports:
    - protocol: TCP
      port: 13000
      targetPort: 13000
  type: ClusterIP
  